'use clinet'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxLayout from "./Redux/ReduxLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxLayout>
        {children}
        </ReduxLayout>

        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.js"></script>

        </body>
    </html>
  );
}
